server:
  port: 8084

spring:
  application:
    name: user-app-service
  datasource:
    url: jdbc:mysql://localhost:3306/bank_issues
    username: root
    password: Nuthan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
